Repository WhiskeySockets/Baileys, pull requests merged in 2025-09, with the labels that each got.

#1677 feat: eventMessage sending / call link creation
  src/Defaults/index.ts
  src/Socket/chats.ts
  src/Socket/messages-send.ts
  src/Types/Message.ts
  src/Utils/messages.ts
Labels: Stale

#1654 Update decode-wa-message.ts (peer_recipient_pn)
  src/Utils/decode-wa-message.ts
Labels: Stale

#1641 fix: message retries loop
  src/Socket/messages-recv.ts
Labels: testing needed

#1627 fix(socket): Prevent crashes from timeouts and fix memory leak
  src/Signal/Group/queue-job.ts
  src/Socket/socket.ts
Labels: bug, testing needed

#1697 Add mutex-based transaction safety to Signal key store (re-reworked)
  src/Signal/Group/group_cipher.ts
  src/Signal/Group/queue-job.ts
  src/Signal/libsignal.ts
  src/Socket/chats.ts
  src/Socket/messages-recv.ts
  src/Socket/messages-send.ts
  src/Socket/socket.ts
  src/Types/Auth.ts
  src/Utils/auth-utils.ts
  src/Utils/decode-wa-message.ts
  src/Utils/process-message.ts
Labels: testing needed

#1820 fix: harden Protobuf Deserialization and Refactor Utilities
  README.md
  src/Defaults/index.ts
  src/Signal/Group/group_cipher.ts
  src/Signal/Group/sender-chain-key.ts
  src/Signal/Group/sender-key-distribution-message.ts
  src/Signal/Group/sender-key-message.ts
  src/Signal/Group/sender-key-record.ts
  src/Signal/Group/sender-key-state.ts
  src/Socket/messages-recv.ts
  src/Socket/socket.ts
  src/Utils/browser-utils.ts
  src/Utils/chat-utils.ts
  src/Utils/decode-wa-message.ts
  src/Utils/generics.ts
  src/Utils/history.ts
  src/Utils/messages-media.ts
  src/Utils/messages.ts
  src/Utils/noise-handler.ts
  src/Utils/process-message.ts
  src/Utils/proto-utils.ts
  src/Utils/validate-connection.ts
  src/WABinary/generic-utils.ts
  src/__tests__/Utils/generics.test.ts
Labels: testing needed
