Repository WhiskeySockets/Baileys, pull requests merged in 2025-07, with the labels that each got.

#1172 [feat]: add/edit/remove contacts
  src/Socket/chats.ts
  src/Types/Chat.ts
  src/Utils/chat-utils.ts
Labels: not fully released, testing needed

#1355 Update to music-metadata from version 7.12.3 to 11.3.0 by switching to Node.js-aware ES module resolution
  package.json
  src/Utils/messages-media.ts
  yarn.lock
Labels: Stale

#1619 Replace deprecated assert with import attributes syntax
  src/Defaults/baileys-version.json
  src/Defaults/baileys-version.ts
  src/Defaults/index.ts
  src/Utils/generics.ts
Labels: testing needed
